### ISSUE TITLE
Integration in openage

### ISSUE THREAD

**Issue by TheJJ** [FolkertVanVerseveld/aoe#1]
Hi!

We, the https://github.com/SFTtech/openage project, would like to motivate you to contribute to our code. We also have fun reinventing wheels by attaching rockets to them, but we attached some rockets already and if we do it right, our engine will support `Rise of Rome` as well.

Of course I can understand if you want to do it on your own for fun, but we both may profit more when we focus on a single engine (which is, say, FUCKIN HARD TO IMPLEMENT anyway).

Cheers,
JJ

**Comment by FolkertVanVerseveld** [comment]
Dear JJ, 

First I want to thank you for your offer. You beat me to it to contact
me first :-P. To be perfectly honest, I have been keeping an eye on
SFTtech and another related OpenAOE project for a couple of months. I
tried to get it up and running on my machine but it never took of. 

I am not sure whether we have the same goals and interests regarding
resurrecting/porting the old Age of Empires franchise, but we will
figure that out soon enough ;-) 

Upcoming weekend, I am going to invest some time getting involved in
OpenAge. My project has a couple of tools (for posix systems only) you
may want to use. I am not sure whether GPLv3 is compatible with AGPLv3
so you/we can reuse it for OpenAge. I can try to relicense those parts
if they are incompatible.

I will keep in touch and let you know how things are going.

Mit freundlichen Grüßen,

Folkert van Verseveld

PS: No, I am Dutch :-P
