### ISSUE TITLE
Makefile: No rule to make target 'game'

### ISSUE THREAD

**Issue by Innoberger** [FolkertVanVerseveld/aoe#23]
When I want to build the game in `/path/to/aoe` with `make`, I get the following error:

`make: *** No rule to make target 'game', needed by 'default'.  Stop.`

Actually there is no game rule/target in the `aoe/Makefile`. I figured out that when out-commenting the `default: genie game` line with `#`, it works pretty much so far.

**Comment by FolkertVanVerseveld** [comment]
Whoops I've incorrectly merged the general Makefile. Thanks for finding this issue. If it still doesn't work, you can reopen this issue.
