### ISSUE TITLE
help me.

### ISSUE THREAD

**Issue by datthanhphu** [FolkertVanVerseveld/aoe#32]
Hi. You. I build it with cygwin sucessed but run have some error. First, i run it show error need all library .dll in cygwin/bin. When i copy all .dll file to folder game and run again program auto close windows game, don't show any error.
You can make vmware os file with all build sucssess or video install?

**Comment by FolkertVanVerseveld** [comment]
Dear Bac Nguyễn Xuan,

Glad to see you have found my project. [Click this](https://github.com/FolkertVanVerseveld/aoe/files/3775978/aoe_prototype_20191027.zip) for windows prototype build including all dlls. The fonts are slightly different due for legal reasons.

If you have the original game on CD-ROM or as an ISO file, you have to insert the CD-ROM or mount the ISO file first before starting empires.exe.

Please be aware it currently is a prototype and there is no game to be played (unfortunately). If you want to build this yourself (as I keep updating and improving the project), you can [click here](https://github.com/FolkertVanVerseveld/aoe/files/3775980/free_fonts.tar.gz) to download all game assets you need to place in genie/. Let me know if you want to help with testing or translating or anything else. Any help is appreciated if you would like to help contributing to this project. You can reply on this issue if you want.

Kind regards,

Folkert van Verseveld

**Comment by datthanhphu** [comment]
Thank you very much
