### ISSUE TITLE
Crash handling

### ISSUE THREAD

**Issue by FolkertVanVerseveld** [FolkertVanVerseveld/aoe#8]
Use gcc backtrace extension, or libunwind or addr2line for backtracing
during a crash to create proper crash logs that can be dumped to a file
for easy bugreporting.

- [x] Choose crash handler
- [x] Create report format
- [x] Test report handling during memory corruption (e.g. corrupt malloc)
- [x] Implement double fault handler

The double fault handler just keeps track whether the crash handler has
been invoked already and calls abort if it's already been called.

**Comment by FolkertVanVerseveld** [comment]
The current crash handler in src/game/empx.c uses backtrace(3) to dump
the symbols with the instruction pointer offset.

We can greatly enhance this if we link against libSegFault as
illustrated here:

[stackoverflow.com/questions/77005/how-to-generate-a-stacktrace-when-my-gcc-c-app-crashes](https://stackoverflow.com/questions/77005/how-to-generate-a-stacktrace-when-my-gcc-c-app-crashes)

We can just try a couple of examples and decide which one works best or
provide the best ones in the configure script.

**Comment by FolkertVanVerseveld** [comment]
As of b8e9610761058b0f9b1bf7c7159c9b1f6e12becb, this issue is closed.

**Comment by darkcharmander** [comment]
Closed issue notification test.
